alter session set "_ORACLE_SCRIPT"=true;

CREATE USER BRUNOXPEIXOTO IDENTIFIED BY BRUNOXPEIXOTO;

GRANT create session TO BRUNOXPEIXOTO;
GRANT create table TO BRUNOXPEIXOTO;
GRANT create view TO BRUNOXPEIXOTO;
GRANT create any trigger TO BRUNOXPEIXOTO;
GRANT create any procedure TO BRUNOXPEIXOTO;
GRANT create sequence TO BRUNOXPEIXOTO;
GRANT create synonym TO BRUNOXPEIXOTO;
GRANT UNLIMITED TABLESPACE TO BRUNOXPEIXOTO;

create sequence BRUNOXPEIXOTO.USERS_ID_SEQ
minvalue 1
maxvalue 9999999999
start with 1
increment by 1
nocache
cycle;


CREATE TABLE BRUNOXPEIXOTO.USERS (
	ID NUMBER(11,0) DEFAULT BRUNOXPEIXOTO.USERS_ID_SEQ.nextval,
	NAME VARCHAR2(250),
	DOC_NUMBER VARCHAR2(200),
	CONSTRAINT USERS_PK PRIMARY KEY (ID),
	CONSTRAINT SYS_C00254259 CHECK ("ID" IS NOT NULL),
	CONSTRAINT SYS_C00254260 CHECK ("NAME" IS NOT NULL),
	CONSTRAINT SYS_C00254261 CHECK ("DOC_NUMBER" IS NOT NULL)
);

quit;